package pojos;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DetallepedidosId generated by hbm2java
 */
@Embeddable
public class DetallepedidosId implements java.io.Serializable {

	private int codigoPedido;
	private String codigoProducto;

	public DetallepedidosId() {
	}

	public DetallepedidosId(int codigoPedido, String codigoProducto) {
		this.codigoPedido = codigoPedido;
		this.codigoProducto = codigoProducto;
	}

	@Column(name = "CodigoPedido", nullable = false)
	public int getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(int codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	@Column(name = "CodigoProducto", nullable = false, length = 15)
	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetallepedidosId))
			return false;
		DetallepedidosId castOther = (DetallepedidosId) other;

		return (this.getCodigoPedido() == castOther.getCodigoPedido())
				&& ((this.getCodigoProducto() == castOther.getCodigoProducto())
						|| (this.getCodigoProducto() != null && castOther.getCodigoProducto() != null
								&& this.getCodigoProducto().equals(castOther.getCodigoProducto())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCodigoPedido();
		result = 37 * result + (getCodigoProducto() == null ? 0 : this.getCodigoProducto().hashCode());
		return result;
	}

}
