package pojos;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empleados generated by hbm2java
 */
@Entity
@Table(name = "empleados", catalog = "jardineria")
public class Empleados implements java.io.Serializable {

	private int codigoEmpleado;
	private Empleados empleados;
	private Oficinas oficinas;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String extension;
	private String email;
	private String puesto;
	private Set<Empleados> empleadoses = new HashSet<Empleados>(0);
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public Empleados() {
	}

	public Empleados(int codigoEmpleado, Oficinas oficinas, String nombre, String apellido1, String extension,
			String email) {
		this.codigoEmpleado = codigoEmpleado;
		this.oficinas = oficinas;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.extension = extension;
		this.email = email;
	}

	public Empleados(int codigoEmpleado, Empleados empleados, Oficinas oficinas, String nombre, String apellido1,
			String apellido2, String extension, String email, String puesto, Set<Empleados> empleadoses,
			Set<Clientes> clienteses) {
		this.codigoEmpleado = codigoEmpleado;
		this.empleados = empleados;
		this.oficinas = oficinas;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.extension = extension;
		this.email = email;
		this.puesto = puesto;
		this.empleadoses = empleadoses;
		this.clienteses = clienteses;
	}

	@Id

	@Column(name = "CodigoEmpleado", unique = true, nullable = false)
	public int getCodigoEmpleado() {
		return this.codigoEmpleado;
	}

	public void setCodigoEmpleado(int codigoEmpleado) {
		this.codigoEmpleado = codigoEmpleado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoJefe")
	public Empleados getEmpleados() {
		return this.empleados;
	}

	public void setEmpleados(Empleados empleados) {
		this.empleados = empleados;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoOficina", nullable = false)
	public Oficinas getOficinas() {
		return this.oficinas;
	}

	public void setOficinas(Oficinas oficinas) {
		this.oficinas = oficinas;
	}

	@Column(name = "Nombre", nullable = false, length = 50)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Apellido1", nullable = false, length = 50)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "Apellido2", length = 50)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "Extension", nullable = false, length = 10)
	public String getExtension() {
		return this.extension;
	}

	public void setExtension(String extension) {
		this.extension = extension;
	}

	@Column(name = "Email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "Puesto", length = 50)
	public String getPuesto() {
		return this.puesto;
	}

	public void setPuesto(String puesto) {
		this.puesto = puesto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleados")
	public Set<Empleados> getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set<Empleados> empleadoses) {
		this.empleadoses = empleadoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "empleados")
	public Set<Clientes> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<Clientes> clienteses) {
		this.clienteses = clienteses;
	}

}
