package pojos;

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Productos generated by hbm2java
 */
@Entity
@Table(name = "productos", catalog = "jardineria")
public class Productos implements java.io.Serializable {

	private String codigoProducto;
	private Gamasproductos gamasproductos;
	private String nombre;
	private String dimensiones;
	private String proveedor;
	private String descripcion;
	private short cantidadEnStock;
	private BigDecimal precioVenta;
	private BigDecimal precioProveedor;
	private Set<Detallepedidos> detallepedidoses = new HashSet<Detallepedidos>(0);

	public Productos() {
	}

	public Productos(String codigoProducto, Gamasproductos gamasproductos, String nombre, short cantidadEnStock,
			BigDecimal precioVenta) {
		this.codigoProducto = codigoProducto;
		this.gamasproductos = gamasproductos;
		this.nombre = nombre;
		this.cantidadEnStock = cantidadEnStock;
		this.precioVenta = precioVenta;
	}

	public Productos(String codigoProducto, Gamasproductos gamasproductos, String nombre, String dimensiones,
			String proveedor, String descripcion, short cantidadEnStock, BigDecimal precioVenta,
			BigDecimal precioProveedor, Set<Detallepedidos> detallepedidoses) {
		this.codigoProducto = codigoProducto;
		this.gamasproductos = gamasproductos;
		this.nombre = nombre;
		this.dimensiones = dimensiones;
		this.proveedor = proveedor;
		this.descripcion = descripcion;
		this.cantidadEnStock = cantidadEnStock;
		this.precioVenta = precioVenta;
		this.precioProveedor = precioProveedor;
		this.detallepedidoses = detallepedidoses;
	}

	@Id

	@Column(name = "CodigoProducto", unique = true, nullable = false, length = 15)
	public String getCodigoProducto() {
		return this.codigoProducto;
	}

	public void setCodigoProducto(String codigoProducto) {
		this.codigoProducto = codigoProducto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Gama", nullable = false)
	public Gamasproductos getGamasproductos() {
		return this.gamasproductos;
	}

	public void setGamasproductos(Gamasproductos gamasproductos) {
		this.gamasproductos = gamasproductos;
	}

	@Column(name = "Nombre", nullable = false, length = 70)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "Dimensiones", length = 25)
	public String getDimensiones() {
		return this.dimensiones;
	}

	public void setDimensiones(String dimensiones) {
		this.dimensiones = dimensiones;
	}

	@Column(name = "Proveedor", length = 50)
	public String getProveedor() {
		return this.proveedor;
	}

	public void setProveedor(String proveedor) {
		this.proveedor = proveedor;
	}

	@Column(name = "Descripcion", length = 65535)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "CantidadEnStock", nullable = false)
	public short getCantidadEnStock() {
		return this.cantidadEnStock;
	}

	public void setCantidadEnStock(short cantidadEnStock) {
		this.cantidadEnStock = cantidadEnStock;
	}

	@Column(name = "PrecioVenta", nullable = false, precision = 15)
	public BigDecimal getPrecioVenta() {
		return this.precioVenta;
	}

	public void setPrecioVenta(BigDecimal precioVenta) {
		this.precioVenta = precioVenta;
	}

	@Column(name = "PrecioProveedor", precision = 15)
	public BigDecimal getPrecioProveedor() {
		return this.precioProveedor;
	}

	public void setPrecioProveedor(BigDecimal precioProveedor) {
		this.precioProveedor = precioProveedor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productos")
	public Set<Detallepedidos> getDetallepedidoses() {
		return this.detallepedidoses;
	}

	public void setDetallepedidoses(Set<Detallepedidos> detallepedidoses) {
		this.detallepedidoses = detallepedidoses;
	}

}
