package pojos;
// Generated 5 feb. 2023 22:56:02 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Empleado generated by hbm2java
 */
@Entity
@Table(name = "empleado", catalog = "Empresa", uniqueConstraints = @UniqueConstraint(columnNames = "dirige"))
public class Empleado implements java.io.Serializable {

	private int nss;
	private Departamento departamentoByDepartamento;
	private Departamento departamentoByDirige;
	private String direccion;
	private String nombre;

	public Empleado() {
	}

	public Empleado(int nss) {
		this.nss = nss;
	}

	public Empleado(int nss, Departamento departamentoByDepartamento, Departamento departamentoByDirige,
			String direccion, String nombre) {
		this.nss = nss;
		this.departamentoByDepartamento = departamentoByDepartamento;
		this.departamentoByDirige = departamentoByDirige;
		this.direccion = direccion;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "nss", unique = true, nullable = false)
	public int getNss() {
		return this.nss;
	}

	public void setNss(int nss) {
		this.nss = nss;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "departamento")
	public Departamento getDepartamentoByDepartamento() {
		return this.departamentoByDepartamento;
	}

	public void setDepartamentoByDepartamento(Departamento departamentoByDepartamento) {
		this.departamentoByDepartamento = departamentoByDepartamento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dirige", unique = true)
	public Departamento getDepartamentoByDirige() {
		return this.departamentoByDirige;
	}

	public void setDepartamentoByDirige(Departamento departamentoByDirige) {
		this.departamentoByDirige = departamentoByDirige;
	}

	@Column(name = "direccion", length = 40)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
