package pojos;
// Generated 5 feb. 2023 22:56:02 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * TiposProyecto generated by hbm2java
 */
@Entity
@Table(name = "Tipos proyecto", catalog = "Empresa")
public class TiposProyecto implements java.io.Serializable {

	private Integer idTipo;
	private String descripcion;
	private Set<Proyecto> proyectos = new HashSet<Proyecto>(0);

	public TiposProyecto() {
	}

	public TiposProyecto(String descripcion, Set<Proyecto> proyectos) {
		this.descripcion = descripcion;
		this.proyectos = proyectos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id tipo", unique = true, nullable = false)
	public Integer getIdTipo() {
		return this.idTipo;
	}

	public void setIdTipo(Integer idTipo) {
		this.idTipo = idTipo;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "proyect-tipo", catalog = "Empresa", joinColumns = {
			@JoinColumn(name = "id_tipo", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "id_proy", nullable = false, updatable = false) })
	public Set<Proyecto> getProyectos() {
		return this.proyectos;
	}

	public void setProyectos(Set<Proyecto> proyectos) {
		this.proyectos = proyectos;
	}

}
