package pojos;

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallepedidos generated by hbm2java
 */
@Entity
@Table(name = "detallepedidos", catalog = "jardineria")
public class Detallepedidos implements java.io.Serializable {

	private DetallepedidosId id;
	private Pedidos pedidos;
	private Productos productos;
	private int cantidad;
	private BigDecimal precioUnidad;
	private short numeroLinea;

	public Detallepedidos() {
	}

	public Detallepedidos(DetallepedidosId id, Pedidos pedidos, Productos productos, int cantidad,
			BigDecimal precioUnidad, short numeroLinea) {
		this.id = id;
		this.pedidos = pedidos;
		this.productos = productos;
		this.cantidad = cantidad;
		this.precioUnidad = precioUnidad;
		this.numeroLinea = numeroLinea;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codigoPedido", column = @Column(name = "CodigoPedido", nullable = false)),
			@AttributeOverride(name = "codigoProducto", column = @Column(name = "CodigoProducto", nullable = false, length = 15)) })
	public DetallepedidosId getId() {
		return this.id;
	}

	public void setId(DetallepedidosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoPedido", nullable = false, insertable = false, updatable = false)
	public Pedidos getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Pedidos pedidos) {
		this.pedidos = pedidos;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoProducto", nullable = false, insertable = false, updatable = false)
	public Productos getProductos() {
		return this.productos;
	}

	public void setProductos(Productos productos) {
		this.productos = productos;
	}

	@Column(name = "Cantidad", nullable = false)
	public int getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(int cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "PrecioUnidad", nullable = false, precision = 15)
	public BigDecimal getPrecioUnidad() {
		return this.precioUnidad;
	}

	public void setPrecioUnidad(BigDecimal precioUnidad) {
		this.precioUnidad = precioUnidad;
	}

	@Column(name = "NumeroLinea", nullable = false)
	public short getNumeroLinea() {
		return this.numeroLinea;
	}

	public void setNumeroLinea(short numeroLinea) {
		this.numeroLinea = numeroLinea;
	}

}
