package pojos;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Oficinas generated by hbm2java
 */
@Entity
@Table(name = "oficinas", catalog = "jardineria")
public class Oficinas implements java.io.Serializable {

	private String codigoOficina;
	private String ciudad;
	private String pais;
	private String region;
	private String codigoPostal;
	private String telefono;
	private String lineaDireccion1;
	private String lineaDireccion2;
	private Set<Empleados> empleadoses = new HashSet<Empleados>(0);

	public Oficinas() {
	}

	public Oficinas(String codigoOficina, String ciudad, String pais, String codigoPostal, String telefono,
			String lineaDireccion1) {
		this.codigoOficina = codigoOficina;
		this.ciudad = ciudad;
		this.pais = pais;
		this.codigoPostal = codigoPostal;
		this.telefono = telefono;
		this.lineaDireccion1 = lineaDireccion1;
	}

	public Oficinas(String codigoOficina, String ciudad, String pais, String region, String codigoPostal,
			String telefono, String lineaDireccion1, String lineaDireccion2, Set<Empleados> empleadoses) {
		this.codigoOficina = codigoOficina;
		this.ciudad = ciudad;
		this.pais = pais;
		this.region = region;
		this.codigoPostal = codigoPostal;
		this.telefono = telefono;
		this.lineaDireccion1 = lineaDireccion1;
		this.lineaDireccion2 = lineaDireccion2;
		this.empleadoses = empleadoses;
	}

	@Id

	@Column(name = "CodigoOficina", unique = true, nullable = false, length = 10)
	public String getCodigoOficina() {
		return this.codigoOficina;
	}

	public void setCodigoOficina(String codigoOficina) {
		this.codigoOficina = codigoOficina;
	}

	@Column(name = "Ciudad", nullable = false, length = 30)
	public String getCiudad() {
		return this.ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	@Column(name = "Pais", nullable = false, length = 50)
	public String getPais() {
		return this.pais;
	}

	public void setPais(String pais) {
		this.pais = pais;
	}

	@Column(name = "Region", length = 50)
	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	@Column(name = "CodigoPostal", nullable = false, length = 10)
	public String getCodigoPostal() {
		return this.codigoPostal;
	}

	public void setCodigoPostal(String codigoPostal) {
		this.codigoPostal = codigoPostal;
	}

	@Column(name = "Telefono", nullable = false, length = 20)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "LineaDireccion1", nullable = false, length = 50)
	public String getLineaDireccion1() {
		return this.lineaDireccion1;
	}

	public void setLineaDireccion1(String lineaDireccion1) {
		this.lineaDireccion1 = lineaDireccion1;
	}

	@Column(name = "LineaDireccion2", length = 50)
	public String getLineaDireccion2() {
		return this.lineaDireccion2;
	}

	public void setLineaDireccion2(String lineaDireccion2) {
		this.lineaDireccion2 = lineaDireccion2;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "oficinas")
	public Set<Empleados> getEmpleadoses() {
		return this.empleadoses;
	}

	public void setEmpleadoses(Set<Empleados> empleadoses) {
		this.empleadoses = empleadoses;
	}

}
