package pojos;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "pagos", catalog = "jardineria")
public class Pagos implements java.io.Serializable {

	private PagosId id;
	private Clientes clientes;
	private String formaPago;
	private Date fechaPago;
	private BigDecimal cantidad;

	public Pagos() {
	}

	public Pagos(PagosId id, Clientes clientes, String formaPago, Date fechaPago, BigDecimal cantidad) {
		this.id = id;
		this.clientes = clientes;
		this.formaPago = formaPago;
		this.fechaPago = fechaPago;
		this.cantidad = cantidad;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "codigoCliente", column = @Column(name = "CodigoCliente", nullable = false)),
			@AttributeOverride(name = "idtransaccion", column = @Column(name = "IDTransaccion", nullable = false, length = 50)) })
	public PagosId getId() {
		return this.id;
	}

	public void setId(PagosId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCliente", nullable = false, insertable = false, updatable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Column(name = "FormaPago", nullable = false, length = 40)
	public String getFormaPago() {
		return this.formaPago;
	}

	public void setFormaPago(String formaPago) {
		this.formaPago = formaPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaPago", nullable = false, length = 10)
	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	@Column(name = "Cantidad", nullable = false, precision = 15)
	public BigDecimal getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(BigDecimal cantidad) {
		this.cantidad = cantidad;
	}

}
