package pojos;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name = "pedidos", catalog = "jardineria")
public class Pedidos implements java.io.Serializable {

	private int codigoPedido;
	private Clientes clientes;
	private Date fechaPedido;
	private Date fechaEsperada;
	private Date fechaEntrega;
	private String estado;
	private String comentarios;
	private Set<Detallepedidos> detallepedidoses = new HashSet<Detallepedidos>(0);

	public Pedidos() {
	}

	public Pedidos(int codigoPedido, Clientes clientes, Date fechaPedido, Date fechaEsperada, String estado) {
		this.codigoPedido = codigoPedido;
		this.clientes = clientes;
		this.fechaPedido = fechaPedido;
		this.fechaEsperada = fechaEsperada;
		this.estado = estado;
	}

	public Pedidos(int codigoPedido, Clientes clientes, Date fechaPedido, Date fechaEsperada, Date fechaEntrega,
			String estado, String comentarios, Set<Detallepedidos> detallepedidoses) {
		this.codigoPedido = codigoPedido;
		this.clientes = clientes;
		this.fechaPedido = fechaPedido;
		this.fechaEsperada = fechaEsperada;
		this.fechaEntrega = fechaEntrega;
		this.estado = estado;
		this.comentarios = comentarios;
		this.detallepedidoses = detallepedidoses;
	}

	@Id

	@Column(name = "CodigoPedido", unique = true, nullable = false)
	public int getCodigoPedido() {
		return this.codigoPedido;
	}

	public void setCodigoPedido(int codigoPedido) {
		this.codigoPedido = codigoPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CodigoCliente", nullable = false)
	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaPedido", nullable = false, length = 10)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaEsperada", nullable = false, length = 10)
	public Date getFechaEsperada() {
		return this.fechaEsperada;
	}

	public void setFechaEsperada(Date fechaEsperada) {
		this.fechaEsperada = fechaEsperada;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "FechaEntrega", length = 10)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "Estado", nullable = false, length = 15)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "Comentarios", length = 65535)
	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedidos")
	public Set<Detallepedidos> getDetallepedidoses() {
		return this.detallepedidoses;
	}

	public void setDetallepedidoses(Set<Detallepedidos> detallepedidoses) {
		this.detallepedidoses = detallepedidoses;
	}

}
