package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ciclista generated by hbm2java
 */
@Entity
@Table(name = "ciclista", catalog = "ciclismo")
public class Ciclista implements java.io.Serializable {

	private Short dorsal;
	private Equipo equipo;
	private String nombre;
	private Date nacimiento;
	private Set<Etapa> etapas = new HashSet<Etapa>(0);
	private Set<Llevar> llevars = new HashSet<Llevar>(0);
	private Set<Premios> premioses = new HashSet<Premios>(0);
	private Set<Puerto> puertos = new HashSet<Puerto>(0);

	public Ciclista() {
	}

	public Ciclista(Equipo equipo, String nombre) {
		this.equipo = equipo;
		this.nombre = nombre;
	}

	public Ciclista(Equipo equipo, String nombre, Date nacimiento, Set<Etapa> etapas, Set<Llevar> llevars,
			Set<Premios> premioses, Set<Puerto> puertos) {
		this.equipo = equipo;
		this.nombre = nombre;
		this.nacimiento = nacimiento;
		this.etapas = etapas;
		this.llevars = llevars;
		this.premioses = premioses;
		this.puertos = puertos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "dorsal", unique = true, nullable = false)
	public Short getDorsal() {
		return this.dorsal;
	}

	public void setDorsal(Short dorsal) {
		this.dorsal = dorsal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nomeq", nullable = false)
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "nacimiento", length = 10)
	public Date getNacimiento() {
		return this.nacimiento;
	}

	public void setNacimiento(Date nacimiento) {
		this.nacimiento = nacimiento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclista")
	public Set<Etapa> getEtapas() {
		return this.etapas;
	}

	public void setEtapas(Set<Etapa> etapas) {
		this.etapas = etapas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclista")
	public Set<Llevar> getLlevars() {
		return this.llevars;
	}

	public void setLlevars(Set<Llevar> llevars) {
		this.llevars = llevars;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "gana", catalog = "ciclismo", joinColumns = {
			@JoinColumn(name = "dorsal", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "premio", nullable = false, updatable = false) })
	public Set<Premios> getPremioses() {
		return this.premioses;
	}

	public void setPremioses(Set<Premios> premioses) {
		this.premioses = premioses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ciclista")
	public Set<Puerto> getPuertos() {
		return this.puertos;
	}

	public void setPuertos(Set<Puerto> puertos) {
		this.puertos = puertos;
	}

}
