package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Equipo generated by hbm2java
 */
@Entity
@Table(name = "equipo", catalog = "ciclismo")
public class Equipo implements java.io.Serializable {

	private String nomeq;
	private String director;
	private Set<Coche> coches = new HashSet<Coche>(0);
	private Set<Representante> representantes = new HashSet<Representante>(0);
	private Set<Ciclista> ciclistas = new HashSet<Ciclista>(0);

	public Equipo() {
	}

	public Equipo(String nomeq) {
		this.nomeq = nomeq;
	}

	public Equipo(String nomeq, String director, Set<Coche> coches, Set<Representante> representantes,
			Set<Ciclista> ciclistas) {
		this.nomeq = nomeq;
		this.director = director;
		this.coches = coches;
		this.representantes = representantes;
		this.ciclistas = ciclistas;
	}

	@Id

	@Column(name = "nomeq", unique = true, nullable = false, length = 25)
	public String getNomeq() {
		return this.nomeq;
	}

	public void setNomeq(String nomeq) {
		this.nomeq = nomeq;
	}

	@Column(name = "director", length = 30)
	public String getDirector() {
		return this.director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Coche> getCoches() {
		return this.coches;
	}

	public void setCoches(Set<Coche> coches) {
		this.coches = coches;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Representante> getRepresentantes() {
		return this.representantes;
	}

	public void setRepresentantes(Set<Representante> representantes) {
		this.representantes = representantes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "equipo")
	public Set<Ciclista> getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Set<Ciclista> ciclistas) {
		this.ciclistas = ciclistas;
	}

}
