package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etapa generated by hbm2java
 */
@Entity
@Table(name = "etapa", catalog = "ciclismo")
public class Etapa implements java.io.Serializable {

	private short netapa;
	private Ciclista ciclista;
	private short km;
	private String salida;
	private String llegada;
	private Set<Puerto> puertos = new HashSet<Puerto>(0);
	private Set<Llevar> llevars = new HashSet<Llevar>(0);

	public Etapa() {
	}

	public Etapa(short netapa, short km, String salida, String llegada) {
		this.netapa = netapa;
		this.km = km;
		this.salida = salida;
		this.llegada = llegada;
	}

	public Etapa(short netapa, Ciclista ciclista, short km, String salida, String llegada, Set<Puerto> puertos,
			Set<Llevar> llevars) {
		this.netapa = netapa;
		this.ciclista = ciclista;
		this.km = km;
		this.salida = salida;
		this.llegada = llegada;
		this.puertos = puertos;
		this.llevars = llevars;
	}

	@Id

	@Column(name = "netapa", unique = true, nullable = false)
	public short getNetapa() {
		return this.netapa;
	}

	public void setNetapa(short netapa) {
		this.netapa = netapa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dorsal")
	public Ciclista getCiclista() {
		return this.ciclista;
	}

	public void setCiclista(Ciclista ciclista) {
		this.ciclista = ciclista;
	}

	@Column(name = "km", nullable = false)
	public short getKm() {
		return this.km;
	}

	public void setKm(short km) {
		this.km = km;
	}

	@Column(name = "salida", nullable = false, length = 35)
	public String getSalida() {
		return this.salida;
	}

	public void setSalida(String salida) {
		this.salida = salida;
	}

	@Column(name = "llegada", nullable = false, length = 35)
	public String getLlegada() {
		return this.llegada;
	}

	public void setLlegada(String llegada) {
		this.llegada = llegada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etapa")
	public Set<Puerto> getPuertos() {
		return this.puertos;
	}

	public void setPuertos(Set<Puerto> puertos) {
		this.puertos = puertos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etapa")
	public Set<Llevar> getLlevars() {
		return this.llevars;
	}

	public void setLlevars(Set<Llevar> llevars) {
		this.llevars = llevars;
	}

}
