package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * GanadoresId generated by hbm2java
 */
@Embeddable
public class GanadoresId implements java.io.Serializable {

	private String nombre;
	private String nomeq;
	private short netapa;

	public GanadoresId() {
	}

	public GanadoresId(String nombre, String nomeq, short netapa) {
		this.nombre = nombre;
		this.nomeq = nomeq;
		this.netapa = netapa;
	}

	@Column(name = "nombre", nullable = false, length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "nomeq", nullable = false, length = 25)
	public String getNomeq() {
		return this.nomeq;
	}

	public void setNomeq(String nomeq) {
		this.nomeq = nomeq;
	}

	@Column(name = "netapa", nullable = false)
	public short getNetapa() {
		return this.netapa;
	}

	public void setNetapa(short netapa) {
		this.netapa = netapa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GanadoresId))
			return false;
		GanadoresId castOther = (GanadoresId) other;

		return ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
				&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getNomeq() == castOther.getNomeq()) || (this.getNomeq() != null
						&& castOther.getNomeq() != null && this.getNomeq().equals(castOther.getNomeq())))
				&& (this.getNetapa() == castOther.getNetapa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getNomeq() == null ? 0 : this.getNomeq().hashCode());
		result = 37 * result + this.getNetapa();
		return result;
	}

}
