package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Llevar generated by hbm2java
 */
@Entity
@Table(name = "llevar", catalog = "ciclismo")
public class Llevar implements java.io.Serializable {

	private LlevarId id;
	private Ciclista ciclista;
	private Etapa etapa;
	private Maillot maillot;

	public Llevar() {
	}

	public Llevar(LlevarId id, Ciclista ciclista, Etapa etapa, Maillot maillot) {
		this.id = id;
		this.ciclista = ciclista;
		this.etapa = etapa;
		this.maillot = maillot;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "netapa", column = @Column(name = "netapa", nullable = false)),
			@AttributeOverride(name = "codigo", column = @Column(name = "codigo", nullable = false, length = 3)) })
	public LlevarId getId() {
		return this.id;
	}

	public void setId(LlevarId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dorsal", nullable = false)
	public Ciclista getCiclista() {
		return this.ciclista;
	}

	public void setCiclista(Ciclista ciclista) {
		this.ciclista = ciclista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "netapa", nullable = false, insertable = false, updatable = false)
	public Etapa getEtapa() {
		return this.etapa;
	}

	public void setEtapa(Etapa etapa) {
		this.etapa = etapa;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "codigo", nullable = false, insertable = false, updatable = false)
	public Maillot getMaillot() {
		return this.maillot;
	}

	public void setMaillot(Maillot maillot) {
		this.maillot = maillot;
	}

}
