package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Maillot generated by hbm2java
 */
@Entity
@Table(name = "maillot", catalog = "ciclismo")
public class Maillot implements java.io.Serializable {

	private String codigo;
	private String tipo;
	private String color;
	private int premio;
	private Set<Llevar> llevars = new HashSet<Llevar>(0);

	public Maillot() {
	}

	public Maillot(String codigo, String tipo, String color, int premio) {
		this.codigo = codigo;
		this.tipo = tipo;
		this.color = color;
		this.premio = premio;
	}

	public Maillot(String codigo, String tipo, String color, int premio, Set<Llevar> llevars) {
		this.codigo = codigo;
		this.tipo = tipo;
		this.color = color;
		this.premio = premio;
		this.llevars = llevars;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false, length = 3)
	public String getCodigo() {
		return this.codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

	@Column(name = "tipo", nullable = false, length = 30)
	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	@Column(name = "color", nullable = false, length = 20)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "premio", nullable = false)
	public int getPremio() {
		return this.premio;
	}

	public void setPremio(int premio) {
		this.premio = premio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "maillot")
	public Set<Llevar> getLlevars() {
		return this.llevars;
	}

	public void setLlevars(Set<Llevar> llevars) {
		this.llevars = llevars;
	}

}
