package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Premios generated by hbm2java
 */
@Entity
@Table(name = "premios", catalog = "ciclismo")
public class Premios implements java.io.Serializable {

	private int codigo;
	private String descripcion;
	private Integer cantidad;
	private Set<Ciclista> ciclistas = new HashSet<Ciclista>(0);

	public Premios() {
	}

	public Premios(int codigo) {
		this.codigo = codigo;
	}

	public Premios(int codigo, String descripcion, Integer cantidad, Set<Ciclista> ciclistas) {
		this.codigo = codigo;
		this.descripcion = descripcion;
		this.cantidad = cantidad;
		this.ciclistas = ciclistas;
	}

	@Id

	@Column(name = "codigo", unique = true, nullable = false)
	public int getCodigo() {
		return this.codigo;
	}

	public void setCodigo(int codigo) {
		this.codigo = codigo;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "premioses")
	public Set<Ciclista> getCiclistas() {
		return this.ciclistas;
	}

	public void setCiclistas(Set<Ciclista> ciclistas) {
		this.ciclistas = ciclistas;
	}

}
