package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Puerto generated by hbm2java
 */
@Entity
@Table(name = "puerto", catalog = "ciclismo")
public class Puerto implements java.io.Serializable {

	private String nompuerto;
	private Ciclista ciclista;
	private Etapa etapa;
	private short altura;
	private String categoria;
	private Double pendiente;

	public Puerto() {
	}

	public Puerto(String nompuerto, Etapa etapa, short altura, String categoria) {
		this.nompuerto = nompuerto;
		this.etapa = etapa;
		this.altura = altura;
		this.categoria = categoria;
	}

	public Puerto(String nompuerto, Ciclista ciclista, Etapa etapa, short altura, String categoria, Double pendiente) {
		this.nompuerto = nompuerto;
		this.ciclista = ciclista;
		this.etapa = etapa;
		this.altura = altura;
		this.categoria = categoria;
		this.pendiente = pendiente;
	}

	@Id

	@Column(name = "nompuerto", unique = true, nullable = false, length = 35)
	public String getNompuerto() {
		return this.nompuerto;
	}

	public void setNompuerto(String nompuerto) {
		this.nompuerto = nompuerto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dorsal")
	public Ciclista getCiclista() {
		return this.ciclista;
	}

	public void setCiclista(Ciclista ciclista) {
		this.ciclista = ciclista;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "netapa", nullable = false)
	public Etapa getEtapa() {
		return this.etapa;
	}

	public void setEtapa(Etapa etapa) {
		this.etapa = etapa;
	}

	@Column(name = "altura", nullable = false)
	public short getAltura() {
		return this.altura;
	}

	public void setAltura(short altura) {
		this.altura = altura;
	}

	@Column(name = "categoria", nullable = false, length = 1)
	public String getCategoria() {
		return this.categoria;
	}

	public void setCategoria(String categoria) {
		this.categoria = categoria;
	}

	@Column(name = "pendiente", precision = 15, scale = 5)
	public Double getPendiente() {
		return this.pendiente;
	}

	public void setPendiente(Double pendiente) {
		this.pendiente = pendiente;
	}

}
