package pojos;
// Generated 15 dic. 2022 9:05:46 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Representante generated by hbm2java
 */
@Entity
@Table(name = "representante", catalog = "ciclismo", uniqueConstraints = @UniqueConstraint(columnNames = "nom_eq"))
public class Representante implements java.io.Serializable {

	private int id;
	private Equipo equipo;
	private String nombre;

	public Representante() {
	}

	public Representante(int id) {
		this.id = id;
	}

	public Representante(int id, Equipo equipo, String nombre) {
		this.id = id;
		this.equipo = equipo;
		this.nombre = nombre;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nom_eq", unique = true)
	public Equipo getEquipo() {
		return this.equipo;
	}

	public void setEquipo(Equipo equipo) {
		this.equipo = equipo;
	}

	@Column(name = "nombre", length = 30)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
